name: CI/CD

on:
  push:
    branches:
      - main
      - test-*
      - feat-*
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11.9

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: arm64
      fail-fast: false  # Ensure other jobs continue even if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }} on ${{ matrix.arch }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies using system package manager on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install ffmpeg python3-pyaudio libegl1 libopengl0 libxkbcommon-x11-0 libglu1-mesa libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0

      - name: Install dependencies using system package manager on Windows
        if: runner.os == 'Windows'
        run: choco install ffmpeg

      - name: Install dependencies using system package manager on macOS
        if: runner.os == 'macOS'
        run: brew install ffmpeg portaudio

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        continue-on-error: true  # Continue the job even if this step fails
        run: pytest

      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: ./test-results

  check_results:
    needs: test  # Ensure this step waits for all 'test' jobs
    runs-on: ubuntu-latest  # You can choose the platform
    steps:
      - name: Check previous jobs' results
        run: |
          if [ "${{ job.status }}" != "success" ]; then
            echo "Some jobs have failed"
            exit 1
          fi

# TODO: add bundling and deployment steps on merging to production branch