name: CI/CD

on:
  push:
    branches:
      - main
      - test-*
      - feat-*
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # TODO: Add additional versions of the platforms you want to test on
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install FFmpeg on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install ffmpeg

      - name: Install FFmpeg on Windows
        if: runner.os == 'Windows'
        run: |
          choco install ffmpeg

      - name: Install FFmpeg on macOS
        if: runner.os == 'macOS'
        run: brew install ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: ./test-results
