name: CI/CD

on:
  push:
    branches:
      - main
      - test-*
      - feat-*
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11.9

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }} on ${{ matrix.arch }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies using system package manager on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install ffmpeg python3-pyaudio libegl1 libopengl0 libxkbcommon-x11-0 libglu1-mesa libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0

      - name: Install dependencies using system package manager on Windows
        if: runner.os == 'Windows'
        run: choco install ffmpeg

      - name: Install dependencies using system package manager on macOS
        if: runner.os == 'macOS'
        run: brew install ffmpeg portaudio

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: ./test-results
