name: CI/CD

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11.9

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: arm64
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }} on ${{ matrix.arch }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install system dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            ffmpeg \
            libegl1 \
            libopengl0 \
            libxkbcommon-x11-0 \
            libglu1-mesa \
            libasound-dev \
            portaudio19-dev \
            libportaudio2 \
            libportaudiocpp0 \
            libxcb-cursor0 \
            xorg-dev \
            libx11-dev \
            qtmultimedia5-dev \
            python3-pyqt5-dev \
            python3-pyqt6-dev

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        run: brew install ffmpeg portaudio

      - name: Set up Xvfb for headless GUI testing
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
          sleep 3
          xset -display :99

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyaudio
          pip install -r requirements.txt

      - name: Run tests with headless GUI support
        run: |
          export TESTQT_DRIVER=headless
          pytest -v --display=:99
